[SP-58] edycja danych lekarza
szczepienia-pw/backend pull request #21
Opened 2022-03-24 21:07 UTC by Brotholomew

1. dodano endpoint put admin/doctors/{doctor-id}
2. dodano obsługę endpointu

testy jednostkowe pojawią się w przyszłych commitach

Signed-off-by: Brotholomew <bartoszek.blach@gmail.com>

2022-03-24 21:13 UTC, lavar3l commented on app/Services/Admin/AdminDoctorsService.cs
> +        private void validateEmail(string email, int? id = null)
Ustaw nazwę funkcji z wielkiej litery 😜

2022-03-25 08:18 UTC, Brotholomew commented on app/Services/Admin/AdminDoctorsService.cs
> +        private void validateEmail(string email, int? id = null)
prywatne funkcje też z dużych liter?

2022-03-25 12:17 UTC, lavar3l commented on app/Services/Admin/AdminDoctorsService.cs
> +        private void validateEmail(string email, int? id = null)
Myślę, że tak. Przy funkcjach protected pisaliśmy z wielkiej.

2022-03-25 14:21 UTC, RazorMeister requested changes
Przenieś zarządzanie doktorem do katalogu w postmanie Admin>Doctor CRUD czy coś takiego

2022-03-26 01:11 UTC, Brotholomew commented on app/Services/Admin/AdminDoctorsService.cs
> +        private void validateEmail(string email, int? id = null)
oki

2022-03-26 01:13 UTC, Brotholomew commented
> Przenieś zarządzanie doktorem do katalogu w postmanie Admin>Doctor CRUD czy coś takiego

ok

2022-03-26 11:09 UTC, lavar3l approved these changes

2022-03-26 11:19 UTC, RazorMeister approved these changes

2022-03-26 11:49 UTC, merged