WIP: [SP-126] added admin -> patient CRUD
szczepienia-pw/backend pull request #25
Opened 2022-03-27 22:13 UTC by Brotholomew

2022-03-27 22:54 UTC, lavar3l requested changes

2022-03-27 22:54 UTC, lavar3l commented on app/Services/Admin/AdminPatientsService.cs
> +
W tym miejscu powinniśmy chyba jeszcze zwolnić ewentualne sloty zarezerwowane (w przyszłości) przez tego pacjenta, żeby inni pacjenci mogli z nich skorzystać.

2022-04-02 20:40 UTC, lavar3l approved these changes

2022-04-10 16:16 UTC, RazorMeister approved these changes

2022-04-10 16:44 UTC, merged